pipeline:
  name: ci pipeline
  identifier: ci_pipeline
  projectIdentifier: ORCA_onedev
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: testinggithub
        repoName: react-pipeline-sample
        build: <+input>
  stages:
    - stage:
        name: stage1
        identifier: stage1
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            paths: []
          buildIntelligence:
            enabled: false
          execution:
            steps:
              - step:
                  type: BuildAndPushGAR
                  name: BuildAndPushGAR_1
                  identifier: BuildAndPushGAR_1
                  spec:
                    connectorRef: serviceaccountgcp
                    host: us-central1-docker.pkg.dev
                    projectID: smooth-keel-441611-d0
                    imageName: testing/hello-app
                    tags:
                      - "1.0"
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
