pipeline:
  name: gcptoharness
  identifier: gcptoharness
  projectIdentifier: ORCA_onedev
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: testinggithub
        repoName: react-pipeline-sample
        build: <+input>
  stages:
    - stage:
        name: build-stage
        identifier: buildstage
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: gcpconnector
              namespace: harness-delegate-ng
              automountServiceAccountToken: true
              nodeSelector: {}
              os: Linux
          execution:
            steps:
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec:
                    connectorRef: gcp
                    image: us-central1-docker.pkg.dev/smooth-keel-441611-d0/testing/nginx
                    shell: Sh
                    command: echo "pushing the image to  gcr"
                  description: checking the image
              - step:
                  type: BuildAndPushGAR
                  name: BuildAndPushGAR_1
                  identifier: BuildAndPushGAR_1
                  spec:
                    connectorRef: gcp
                    host: us-central1-docker.pkg.dev
                    projectID: smooth-keel-441611-d0
                    imageName: testing/nginx
                    tags:
                      - v1
          caching:
            enabled: true
            paths: []
          buildIntelligence:
            enabled: false
